version: '3'

services:
  postgresql:
    container_name: postgresql_container
    build: ./postgresql
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgresql/ddl:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
    restart: always